### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by mrbell11** [CasualYT31/tiktoknotifier#1]
Hey I'm getting this error when I try to start the bot

```
COULDN'T READ FROM CONFIG FILE: [Errno 2] No such file or directory: './config.json'
Traceback (most recent call last):
  File "/home/container/main.py", line 26, in <module>
    from bot import initialise_bot
  File "/home/container/bot.py", line 32, in <module>
    from config import update_setting, Setting, delete_discord_user, delete_setting, \
  File "/home/container/config.py", line 57, in <module>
    __CONFIG_USERNAMES = list(__CONFIG_CACHE.keys())
                              ^^^^^^^^^^^^^^
NameError: name '__CONFIG_CACHE' is not defined. Did you mean: '__CONFIG_LOCK'?
```

**Comment by CasualYT31** [comment]
@mrbell11 Thanks for the report, should be fixed now.
